version: "3"

services:

  wordpress:
    image: wordpress:5.5
    container_name: wordpress
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /src:/var/www/html
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: ${MYSQL_HOST}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}   
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}

  nginx:
    image: linuxserver/letsencrypt
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/config:/config
      - ./docker/nginx/nginx.conf:/config/nginx/site-confs/default
      - ./docker/nginx/ssl.conf:/config/nginx/ssl.conf
    container_name: nginx
    restart: unless-stopped
    environment: 
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - URL=proyectos-eafit.tk  
      - SUBDOMAINS=www,    
      - EMAIL=jpablopena8spm@gmail.com 
      - VALIDATION=http
      - STAGING=false 
      