version: "3"

services:

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password  
    container_name: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/configs/my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
    restart: always
    env_file: .env 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}   